name: Scan jdk8-postgres15 Docker image

on:
  pull_request:
    paths:
      - jdk-postgres/8-15/**
  schedule:
  - cron: "0 0 * * 3" # every Wednesday

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the Docker image locally for scanning
      run: |
        LAST_JDK8_VERSION=$(git tag | grep jdk8 | sed 's/jdk8-//g' | sort -r --version-sort | head -n 1)
        echo "Scan with the base image version: $LAST_JDK8_VERSION"
        docker build ./jdk-postgres/8-15 --build-arg BASE_IMAGE_VERSION="$LAST_JDK8_VERSION" -t can_be_removed

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: can_be_removed
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
