name: Scan jre/8 Docker image

on:
  push:
    paths:
      - jre/8/**
  schedule:
  - cron: "0 0 * * 3" # every Wednesday

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image locally for scanning
      run: docker build ./jre/8 -t can_be_removed

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: can_be_removed
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
