name: Build and push the Docker image for JRE 8

on:
  push:
    tags:
      - "jre8-[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/jre8-##g")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Check out codes
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ghcr.io/scalar-labs/jre8:${{ steps.version.outputs.version }} ./jre/8

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/scalar-labs/jre8:${{ steps.version.outputs.version }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image
        run: docker push ghcr.io/scalar-labs/jre8:${{ steps.version.outputs.version }}
